/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DiscretizarGUI.java
 *
 * Created on 16/11/2010, 06:24:31 AM
 */

package GUI;

/**
 *
 * @author Gema
 */
public class DiscretizarGUI extends javax.swing.JFrame {
    int valorIntervalo;

    /** Creates new form DiscretizarGUI */
    public DiscretizarGUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSpinnerDiscretizar = new javax.swing.JSpinner();
        jLabelIntervalosDisc = new javax.swing.JLabel();
        jButtonGUIDiscretizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(":.Discretizar Atributos Numericos.:");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jSpinnerDiscretizar.setModel(new javax.swing.SpinnerNumberModel(2, 2, 50, 1));

        jLabelIntervalosDisc.setText("Intervalos");

        jButtonGUIDiscretizar.setText("Discretizar");
        jButtonGUIDiscretizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGUIDiscretizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabelIntervalosDisc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jSpinnerDiscretizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jButtonGUIDiscretizar)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerDiscretizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIntervalosDisc))
                .addGap(54, 54, 54)
                .addComponent(jButtonGUIDiscretizar)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGUIDiscretizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGUIDiscretizarActionPerformed
        // TODO add your handling code here:
        valorIntervalo=0;
        valorIntervalo=Integer.parseInt(jSpinnerDiscretizar.getValue().toString());
        System.out.print("Intervalo: "+valorIntervalo);
        this.show(false);
    }//GEN-LAST:event_jButtonGUIDiscretizarActionPerformed

    public int getValorIntervalo()
    {
        System.out.print("Intervalo: "+valorIntervalo);
        return valorIntervalo;
    }
    /**
    * @param args the command line arguments
    */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DiscretizarGUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGUIDiscretizar;
    private javax.swing.JLabel jLabelIntervalosDisc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerDiscretizar;
    // End of variables declaration//GEN-END:variables

}
